FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=changeme
ENV MYSQL_DATABASE=mdtest2
ENV MYSQL_USER=mdtest_user
ENV MYSQL_PASSWORD=changeme

COPY proyecto2.sql /docker-entrypoint-initdb.d/1-schema.sql
COPY mejoras_db.sql /docker-entrypoint-initdb.d/2-mejoras.sql

EXPOSE 3306
